### ISSUE TITLE
Old dependencies.

### ISSUE THREAD

**Issue by ScriptWorker** [rxaviers/react-globalize-webpack-plugin#27]
This plugin has old dependencies for packages:
globalize-webpack-plugin@0.4.0,
skip-amd-webpack-plugin@0.1.3

Sorry for additional question in issue, but it is not clear from readme...
I'm trying to find a way to bundle globalize messages for react-globalize, is this the right plugin to achieve this?

I've tried globalize-webpack-plugin@2.0.1, it works for development (without hot reloading for some reason), but I can't bundle code for production as I do not use Globalize.formatMessage function in my code.

**Comment by rxaviers** [comment]
I have just pushed a series of releases. See this table for details https://github.com/rxaviers/react-globalize-webpack-plugin#webpack-react-and-globalize-versions

Please, give it a try and let me know in case you find any troubles.

**Comment by ScriptWorker** [comment]
Thank you for the fix, it works now with latest webpack.

May I ask one more question: are you going to merge fix-5 branch for globalize-webpack-plugin anytime soon? It solves HMR issue.
