### ISSUE TITLE
Phrase extraction produces the wrong key from formatMessage calls

### ISSUE THREAD

**Issue by alunny** [rxaviers/react-globalize-webpack-plugin#3]
Currently react-globalize-webpack-plugin incorrectly extracts calls to formatMessage, so calls like this:

``` js
Globalize.formatMessage('Search Twitter')
```

result in the key `'Search Twitter'` instead of `Search Twitter`. This is possibly due to calling JSON.stringify on a string somewhere, or of a bug in the AST traversal.

I had a look at the code but it's not clear to me yet in which module this is happening - react-globalize-webpack-plugin, globalize-webpack-plugin, react-globalize-compiler, or globalize-compiler.

**Comment by rxaviers** [comment]
Confirmed! Working on a fix at https://github.com/rxaviers/react-globalize-compiler/issues/1

**Comment by rxaviers** [comment]
Fixed by react-globalize-compiler 0.0.3, `npm update` should do it for you. Please, just let me know on any problems.

**Comment by alunny** [comment]
Thanks Rafael!
